/**
 * 内置词库：成人本科（理工类）英语高频词。
 * 字段：word 单词 / phonetic 美式音标 / meaning 释义 / phrase 搭配短语 / phrase_meaning 短语释义 / level 分级
 * level: 1 高频 / 2 核心 / 3 拓展
 */
export interface BuiltinWord {
  word: string;
  phonetic: string;
  meaning: string;
  phrase?: string;
  phrase_meaning?: string;
  level: 1 | 2 | 3;
}

export const BUILTIN_VOCABULARY: BuiltinWord[] = [
  // ===== 1 高频 =====
  { word: 'ability', phonetic: '/əˈbɪləti/', meaning: '能力', phrase: 'demonstrate ability', phrase_meaning: '展示能力', level: 1 },
  { word: 'achieve', phonetic: '/əˈtʃiːv/', meaning: '实现；达到', phrase: 'achieve success', phrase_meaning: '取得成功', level: 1 },
  { word: 'advantage', phonetic: '/ədˈvæntɪdʒ/', meaning: '优势；有利条件', phrase: 'take advantage of', phrase_meaning: '利用', level: 1 },
  { word: 'affect', phonetic: '/əˈfekt/', meaning: '影响', phrase: 'affect the result', phrase_meaning: '影响结果', level: 1 },
  { word: 'allow', phonetic: '/əˈlaʊ/', meaning: '允许', phrase: 'allow sb to do', phrase_meaning: '允许某人做', level: 1 },
  { word: 'amount', phonetic: '/əˈmaʊnt/', meaning: '数量；总额', phrase: 'a large amount of', phrase_meaning: '大量的', level: 1 },
  { word: 'attention', phonetic: '/əˈtenʃn/', meaning: '注意；关注', phrase: 'pay attention to', phrase_meaning: '注意', level: 1 },
  { word: 'avoid', phonetic: '/əˈvɔɪd/', meaning: '避免', phrase: 'avoid mistakes', phrase_meaning: '避免错误', level: 1 },
  { word: 'basic', phonetic: '/ˈbeɪsɪk/', meaning: '基本的', phrase: 'basic knowledge', phrase_meaning: '基础知识', level: 1 },
  { word: 'benefit', phonetic: '/ˈbenɪfɪt/', meaning: '益处；使受益', phrase: 'benefit from', phrase_meaning: '从中受益', level: 1 },
  { word: 'cause', phonetic: '/kɔːz/', meaning: '原因；导致', phrase: 'cause and effect', phrase_meaning: '因果关系', level: 1 },
  { word: 'common', phonetic: '/ˈkɑːmən/', meaning: '常见的；共同的', phrase: 'common sense', phrase_meaning: '常识', level: 1 },
  { word: 'complete', phonetic: '/kəmˈpliːt/', meaning: '完成；完整的', phrase: 'complete a task', phrase_meaning: '完成任务', level: 1 },
  { word: 'consider', phonetic: '/kənˈsɪdər/', meaning: '考虑', phrase: 'consider doing', phrase_meaning: '考虑做某事', level: 1 },
  { word: 'continue', phonetic: '/kənˈtɪnjuː/', meaning: '继续', phrase: 'continue to grow', phrase_meaning: '继续成长', level: 1 },
  { word: 'control', phonetic: '/kənˈtroʊl/', meaning: '控制', phrase: 'take control of', phrase_meaning: '控制', level: 1 },
  { word: 'create', phonetic: '/kriˈeɪt/', meaning: '创造；创建', phrase: 'create an opportunity', phrase_meaning: '创造机会', level: 1 },
  { word: 'culture', phonetic: '/ˈkʌltʃər/', meaning: '文化', phrase: 'traditional culture', phrase_meaning: '传统文化', level: 1 },
  { word: 'decide', phonetic: '/dɪˈsaɪd/', meaning: '决定', phrase: 'decide to do', phrase_meaning: '决定做', level: 1 },
  { word: 'develop', phonetic: '/dɪˈveləp/', meaning: '发展；开发', phrase: 'develop skills', phrase_meaning: '培养技能', level: 1 },
  { word: 'difference', phonetic: '/ˈdɪfrəns/', meaning: '差异', phrase: 'make a difference', phrase_meaning: '产生影响', level: 1 },
  { word: 'difficult', phonetic: '/ˈdɪfɪkəlt/', meaning: '困难的', phrase: 'difficult question', phrase_meaning: '难题', level: 1 },
  { word: 'direction', phonetic: '/dəˈrekʃn/', meaning: '方向', phrase: 'in the direction of', phrase_meaning: '朝……方向', level: 1 },
  { word: 'discuss', phonetic: '/dɪˈskʌs/', meaning: '讨论', phrase: 'discuss a topic', phrase_meaning: '讨论话题', level: 1 },
  { word: 'effect', phonetic: '/ɪˈfekt/', meaning: '效果；影响', phrase: 'side effect', phrase_meaning: '副作用', level: 1 },
  { word: 'effort', phonetic: '/ˈefərt/', meaning: '努力', phrase: 'make an effort', phrase_meaning: '努力', level: 1 },
  { word: 'energy', phonetic: '/ˈenərdʒi/', meaning: '能量；精力', phrase: 'save energy', phrase_meaning: '节约能源', level: 1 },
  { word: 'enough', phonetic: '/ɪˈnʌf/', meaning: '足够的', phrase: 'enough time', phrase_meaning: '足够的时间', level: 1 },
  { word: 'environment', phonetic: '/ɪnˈvaɪrənmənt/', meaning: '环境', phrase: 'protect the environment', phrase_meaning: '保护环境', level: 1 },
  { word: 'example', phonetic: '/ɪɡˈzæmpəl/', meaning: '例子', phrase: 'for example', phrase_meaning: '例如', level: 1 },
  { word: 'explain', phonetic: '/ɪkˈspleɪn/', meaning: '解释', phrase: 'explain the reason', phrase_meaning: '解释原因', level: 1 },
  { word: 'express', phonetic: '/ɪkˈspres/', meaning: '表达', phrase: 'express feelings', phrase_meaning: '表达情感', level: 1 },
  { word: 'important', phonetic: '/ɪmˈpɔːrtnt/', meaning: '重要的', phrase: 'be important to', phrase_meaning: '对……重要', level: 1 },
  { word: 'improve', phonetic: '/ɪmˈpruːv/', meaning: '改进；提高', phrase: 'improve efficiency', phrase_meaning: '提高效率', level: 1 },
  { word: 'include', phonetic: '/ɪnˈkluːd/', meaning: '包括', phrase: 'include details', phrase_meaning: '包含细节', level: 1 },
  { word: 'increase', phonetic: '/ɪnˈkriːs/', meaning: '增加', phrase: 'increase by 10%', phrase_meaning: '增加 10%', level: 1 },
  { word: 'knowledge', phonetic: '/ˈnɑːlɪdʒ/', meaning: '知识', phrase: 'gain knowledge', phrase_meaning: '获取知识', level: 1 },
  { word: 'language', phonetic: '/ˈlæŋɡwɪdʒ/', meaning: '语言', phrase: 'foreign language', phrase_meaning: '外语', level: 1 },
  { word: 'level', phonetic: '/ˈlevəl/', meaning: '水平；等级', phrase: 'at the same level', phrase_meaning: '在同一水平', level: 1 },
  { word: 'main', phonetic: '/meɪn/', meaning: '主要的', phrase: 'main point', phrase_meaning: '要点', level: 1 },
  // ===== 2 核心 =====
  { word: 'analyze', phonetic: '/ˈænəlaɪz/', meaning: '分析', phrase: 'analyze the data', phrase_meaning: '分析数据', level: 2 },
  { word: 'approach', phonetic: '/əˈproʊtʃ/', meaning: '方法；接近', phrase: 'an effective approach', phrase_meaning: '有效方法', level: 2 },
  { word: 'assume', phonetic: '/əˈsuːm/', meaning: '假设；认为', phrase: 'assume that', phrase_meaning: '假定', level: 2 },
  { word: 'attempt', phonetic: '/əˈtempt/', meaning: '尝试', phrase: 'attempt to do', phrase_meaning: '尝试做', level: 2 },
  { word: 'available', phonetic: '/əˈveɪləbəl/', meaning: '可用的', phrase: 'be available to', phrase_meaning: '可供使用', level: 2 },
  { word: 'capacity', phonetic: '/kəˈpæsəti/', meaning: '容量；能力', phrase: 'learning capacity', phrase_meaning: '学习能力', level: 2 },
  { word: 'challenge', phonetic: '/ˈtʃælɪndʒ/', meaning: '挑战', phrase: 'face a challenge', phrase_meaning: '面对挑战', level: 2 },
  { word: 'complex', phonetic: '/ˈkɑːmpleks/', meaning: '复杂的', phrase: 'complex problem', phrase_meaning: '复杂问题', level: 2 },
  { word: 'concept', phonetic: '/ˈkɑːnsept/', meaning: '概念', phrase: 'basic concept', phrase_meaning: '基本概念', level: 2 },
  { word: 'conclusion', phonetic: '/kənˈkluːʒn/', meaning: '结论', phrase: 'draw a conclusion', phrase_meaning: '得出结论', level: 2 },
  { word: 'condition', phonetic: '/kənˈdɪʃn/', meaning: '条件；状况', phrase: 'living conditions', phrase_meaning: '生活条件', level: 2 },
  { word: 'consequence', phonetic: '/ˈkɑːnsəkwens/', meaning: '结果；后果', phrase: 'as a consequence', phrase_meaning: '因此', level: 2 },
  { word: 'contribute', phonetic: '/kənˈtrɪbjuːt/', meaning: '贡献；促成', phrase: 'contribute to', phrase_meaning: '有助于', level: 2 },
  { word: 'critical', phonetic: '/ˈkrɪtɪkəl/', meaning: '关键的；批判的', phrase: 'critical thinking', phrase_meaning: '批判性思维', level: 2 },
  { word: 'current', phonetic: '/ˈkɜːrənt/', meaning: '当前的', phrase: 'current situation', phrase_meaning: '现状', level: 2 },
  { word: 'decline', phonetic: '/dɪˈklaɪn/', meaning: '下降；拒绝', phrase: 'in decline', phrase_meaning: '在下降', level: 2 },
  { word: 'define', phonetic: '/dɪˈfaɪn/', meaning: '定义', phrase: 'define a term', phrase_meaning: '定义术语', level: 2 },
  { word: 'demonstrate', phonetic: '/ˈdemənstreɪt/', meaning: '证明；演示', phrase: 'demonstrate ability', phrase_meaning: '展示能力', level: 2 },
  { word: 'describe', phonetic: '/dɪˈskraɪb/', meaning: '描述', phrase: 'describe a process', phrase_meaning: '描述过程', level: 2 },
  { word: 'determine', phonetic: '/dɪˈtɜːrmɪn/', meaning: '决定；确定', phrase: 'determine the outcome', phrase_meaning: '决定结果', level: 2 },
  { word: 'economic', phonetic: '/ˌiːkəˈnɑːmɪk/', meaning: '经济的', phrase: 'economic growth', phrase_meaning: '经济增长', level: 2 },
  { word: 'efficient', phonetic: '/ɪˈfɪʃnt/', meaning: '高效的', phrase: 'efficient method', phrase_meaning: '高效方法', level: 2 },
  { word: 'eliminate', phonetic: '/ɪˈlɪmɪneɪt/', meaning: '消除；淘汰', phrase: 'eliminate errors', phrase_meaning: '消除错误', level: 2 },
  { word: 'emphasize', phonetic: '/ˈemfəsaɪz/', meaning: '强调', phrase: 'emphasize the importance', phrase_meaning: '强调重要性', level: 2 },
  { word: 'establish', phonetic: '/ɪˈstæblɪʃ/', meaning: '建立', phrase: 'establish a system', phrase_meaning: '建立体系', level: 2 },
  { word: 'evaluate', phonetic: '/ɪˈvæljueɪt/', meaning: '评估', phrase: 'evaluate performance', phrase_meaning: '评估表现', level: 2 },
  { word: 'evidence', phonetic: '/ˈevɪdəns/', meaning: '证据', phrase: 'scientific evidence', phrase_meaning: '科学证据', level: 2 },
  { word: 'expand', phonetic: '/ɪkˈspænd/', meaning: '扩大；扩展', phrase: 'expand the scope', phrase_meaning: '扩大范围', level: 2 },
  { word: 'experience', phonetic: '/ɪkˈspɪriəns/', meaning: '经验；经历', phrase: 'work experience', phrase_meaning: '工作经验', level: 2 },
  { word: 'factor', phonetic: '/ˈfæktər/', meaning: '因素', phrase: 'key factor', phrase_meaning: '关键因素', level: 2 },
  { word: 'feature', phonetic: '/ˈfiːtʃər/', meaning: '特征', phrase: 'main feature', phrase_meaning: '主要特征', level: 2 },
  { word: 'focus', phonetic: '/ˈfoʊkəs/', meaning: '专注；焦点', phrase: 'focus on', phrase_meaning: '专注于', level: 2 },
  { word: 'function', phonetic: '/ˈfʌŋkʃn/', meaning: '功能；运作', phrase: 'basic function', phrase_meaning: '基本功能', level: 2 },
  { word: 'generate', phonetic: '/ˈdʒenəreɪt/', meaning: '产生；生成', phrase: 'generate ideas', phrase_meaning: '产生想法', level: 2 },
  { word: 'impact', phonetic: '/ˈɪmpækt/', meaning: '影响', phrase: 'have an impact on', phrase_meaning: '对……有影响', level: 2 },
  { word: 'individual', phonetic: '/ˌɪndɪˈvɪdʒuəl/', meaning: '个人的；个体', phrase: 'individual needs', phrase_meaning: '个人需求', level: 2 },
  { word: 'innovation', phonetic: '/ˌɪnəˈveɪʃn/', meaning: '创新', phrase: 'technological innovation', phrase_meaning: '技术创新', level: 2 },
  { word: 'investigate', phonetic: '/ɪnˈvestɪɡeɪt/', meaning: '调查', phrase: 'investigate a case', phrase_meaning: '调查案件', level: 2 },
  { word: 'maintain', phonetic: '/meɪnˈteɪn/', meaning: '维持；维护', phrase: 'maintain balance', phrase_meaning: '保持平衡', level: 2 },
  { word: 'method', phonetic: '/ˈmeθəd/', meaning: '方法', phrase: 'teaching method', phrase_meaning: '教学方法', level: 2 },
  // ===== 3 拓展 =====
  { word: 'abstract', phonetic: '/ˈæbstrækt/', meaning: '抽象的', phrase: 'abstract concept', phrase_meaning: '抽象概念', level: 3 },
  { word: 'accelerate', phonetic: '/əkˈseləreɪt/', meaning: '加速', phrase: 'accelerate growth', phrase_meaning: '加速增长', level: 3 },
  { word: 'accommodate', phonetic: '/əˈkɑːmədeɪt/', meaning: '容纳；适应', phrase: 'accommodate changes', phrase_meaning: '适应变化', level: 3 },
  { word: 'accumulate', phonetic: '/əˈkjuːmjəleɪt/', meaning: '积累', phrase: 'accumulate experience', phrase_meaning: '积累经验', level: 3 },
  { word: 'alternative', phonetic: '/ɔːlˈtɜːrnətɪv/', meaning: '替代的；备选方案', phrase: 'alternative solution', phrase_meaning: '替代方案', level: 3 },
  { word: 'ambiguous', phonetic: '/æmˈbɪɡjuəs/', meaning: '模糊的', phrase: 'ambiguous meaning', phrase_meaning: '歧义', level: 3 },
  { word: 'anticipate', phonetic: '/ænˈtɪsɪpeɪt/', meaning: '预期；预见', phrase: 'anticipate problems', phrase_meaning: '预见问题', level: 3 },
  { word: 'apparent', phonetic: '/əˈpærənt/', meaning: '明显的', phrase: 'apparent difference', phrase_meaning: '明显差异', level: 3 },
  { word: 'arbitrary', phonetic: '/ˈɑːrbətreri/', meaning: '任意的；武断的', phrase: 'arbitrary decision', phrase_meaning: '武断决定', level: 3 },
  { word: 'artificial', phonetic: '/ˌɑːrtɪˈfɪʃəl/', meaning: '人工的；人造的', phrase: 'artificial intelligence', phrase_meaning: '人工智能', level: 3 },
  { word: 'assess', phonetic: '/əˈses/', meaning: '评估；评定', phrase: 'assess the risk', phrase_meaning: '评估风险', level: 3 },
  { word: 'attribute', phonetic: '/əˈtrɪbjuːt/', meaning: '归因于；属性', phrase: 'attribute to', phrase_meaning: '归因于', level: 3 },
  { word: 'constitute', phonetic: '/ˈkɑːnstɪtuːt/', meaning: '构成', phrase: 'constitute a threat', phrase_meaning: '构成威胁', level: 3 },
  { word: 'contradict', phonetic: '/ˌkɑːntrəˈdɪkt/', meaning: '反驳；相矛盾', phrase: 'contradict the theory', phrase_meaning: '与理论相悖', level: 3 },
  { word: 'controversial', phonetic: '/ˌkɑːntrəˈvɜːrʃəl/', meaning: '有争议的', phrase: 'controversial issue', phrase_meaning: '争议问题', level: 3 },
  { word: 'criterion', phonetic: '/kraɪˈtɪriən/', meaning: '标准', phrase: 'evaluation criterion', phrase_meaning: '评价标准', level: 3 },
  { word: 'crucial', phonetic: '/ˈkruːʃəl/', meaning: '至关重要的', phrase: 'crucial role', phrase_meaning: '关键作用', level: 3 },
  { word: 'deduce', phonetic: '/dɪˈduːs/', meaning: '推断', phrase: 'deduce a conclusion', phrase_meaning: '推断结论', level: 3 },
  { word: 'deficient', phonetic: '/dɪˈfɪʃnt/', meaning: '缺乏的', phrase: 'be deficient in', phrase_meaning: '缺乏', level: 3 },
  { word: 'differentiate', phonetic: '/ˌdɪfəˈrenʃieɪt/', meaning: '区分', phrase: 'differentiate between', phrase_meaning: '区分', level: 3 },
  { word: 'dilemma', phonetic: '/dɪˈlemə/', meaning: '困境', phrase: 'face a dilemma', phrase_meaning: '面临两难', level: 3 },
  { word: 'diminish', phonetic: '/dɪˈmɪnɪʃ/', meaning: '减少；减弱', phrase: 'diminish the effect', phrase_meaning: '削弱影响', level: 3 },
  { word: 'elaborate', phonetic: '/ɪˈlæbərət/', meaning: '精心制作的；详述', phrase: 'elaborate plan', phrase_meaning: '周密计划', level: 3 },
  { word: 'empirical', phonetic: '/ɪmˈpɪrɪkəl/', meaning: '经验的；实证的', phrase: 'empirical evidence', phrase_meaning: '实证证据', level: 3 },
  { word: 'enhance', phonetic: '/ɪnˈhæns/', meaning: '增强；提高', phrase: 'enhance quality', phrase_meaning: '提升质量', level: 3 },
  { word: 'feasible', phonetic: '/ˈfiːzəbəl/', meaning: '可行的', phrase: 'feasible plan', phrase_meaning: '可行方案', level: 3 },
  { word: 'fluctuate', phonetic: '/ˈflʌktʃueɪt/', meaning: '波动', phrase: 'fluctuate over time', phrase_meaning: '随时间波动', level: 3 },
  { word: 'fundamental', phonetic: '/ˌfʌndəˈmentl/', meaning: '基本的；根本的', phrase: 'fundamental principle', phrase_meaning: '基本原理', level: 3 },
  { word: 'hypothesis', phonetic: '/haɪˈpɑːθəsɪs/', meaning: '假设', phrase: 'test a hypothesis', phrase_meaning: '检验假设', level: 3 },
  { word: 'inevitable', phonetic: '/ɪnˈevɪtəbəl/', meaning: '不可避免的', phrase: 'inevitable result', phrase_meaning: '必然结果', level: 3 },
  { word: 'integrate', phonetic: '/ˈɪntɪɡreɪt/', meaning: '整合；融入', phrase: 'integrate into', phrase_meaning: '融入', level: 3 },
  { word: 'legitimate', phonetic: '/lɪˈdʒɪtɪmət/', meaning: '合法的；合理的', phrase: 'legitimate concern', phrase_meaning: '合理关切', level: 3 },
  { word: 'manipulate', phonetic: '/məˈnɪpjəleɪt/', meaning: '操纵', phrase: 'manipulate data', phrase_meaning: '操纵数据', level: 3 },
  { word: 'phenomenon', phonetic: '/fəˈnɑːmɪnən/', meaning: '现象', phrase: 'natural phenomenon', phrase_meaning: '自然现象', level: 3 },
  { word: 'precise', phonetic: '/prɪˈsaɪs/', meaning: '精确的', phrase: 'precise measurement', phrase_meaning: '精确测量', level: 3 },
  { word: 'profound', phonetic: '/prəˈfaʊnd/', meaning: '深刻的', phrase: 'profound impact', phrase_meaning: '深远影响', level: 3 },
  { word: 'rational', phonetic: '/ˈræʃnəl/', meaning: '理性的', phrase: 'rational decision', phrase_meaning: '理性决策', level: 3 },
  { word: 'significant', phonetic: '/sɪɡˈnɪfɪkənt/', meaning: '显著的；重要的', phrase: 'significant progress', phrase_meaning: '显著进展', level: 3 },
  { word: 'sophisticated', phonetic: '/səˈfɪstɪkeɪtɪd/', meaning: '复杂的；精密的', phrase: 'sophisticated technology', phrase_meaning: '精密技术', level: 3 },
  { word: 'transform', phonetic: '/trænsˈfɔːrm/', meaning: '转变；改造', phrase: 'transform the industry', phrase_meaning: '变革行业', level: 3 },
];

export const BUILTIN_DECK_NAME = '内置高频词库';

/** 第二批：扩充高频核心词（成考/四级高频，认识为主） */
export const BUILTIN_VOCABULARY_2: BuiltinWord[] = [
  // ===== 1 高频 =====
  { word: 'activity', phonetic: '/ækˈtɪvəti/', meaning: '活动', phrase: 'outdoor activity', phrase_meaning: '户外活动', level: 1 },
  { word: 'admit', phonetic: '/ədˈmɪt/', meaning: '承认；准许进入', phrase: 'admit a mistake', phrase_meaning: '承认错误', level: 1 },
  { word: 'advice', phonetic: '/ədˈvaɪs/', meaning: '建议', phrase: 'give advice', phrase_meaning: '给出建议', level: 1 },
  { word: 'agree', phonetic: '/əˈɡriː/', meaning: '同意', phrase: 'agree with', phrase_meaning: '同意', level: 1 },
  { word: 'aim', phonetic: '/eɪm/', meaning: '目标；瞄准', phrase: 'aim at', phrase_meaning: '旨在', level: 1 },
  { word: 'appear', phonetic: '/əˈpɪr/', meaning: '出现；似乎', phrase: 'appear to be', phrase_meaning: '似乎是', level: 1 },
  { word: 'argue', phonetic: '/ˈɑːrɡjuː/', meaning: '争论；主张', phrase: 'argue that', phrase_meaning: '主张', level: 1 },
  { word: 'arrange', phonetic: '/əˈreɪndʒ/', meaning: '安排；整理', phrase: 'arrange a meeting', phrase_meaning: '安排会议', level: 1 },
  { word: 'article', phonetic: '/ˈɑːrtɪkəl/', meaning: '文章；物品', phrase: 'read an article', phrase_meaning: '读文章', level: 1 },
  { word: 'attend', phonetic: '/əˈtend/', meaning: '出席；照料', phrase: 'attend class', phrase_meaning: '上课', level: 1 },
  { word: 'attract', phonetic: '/əˈtrækt/', meaning: '吸引', phrase: 'attract attention', phrase_meaning: '吸引注意', level: 1 },
  { word: 'average', phonetic: '/ˈævərɪdʒ/', meaning: '平均的；平均', phrase: 'on average', phrase_meaning: '平均而言', level: 1 },
  { word: 'aware', phonetic: '/əˈwer/', meaning: '意识到的', phrase: 'be aware of', phrase_meaning: '意识到', level: 1 },
  { word: 'background', phonetic: '/ˈbækɡraʊnd/', meaning: '背景', phrase: 'cultural background', phrase_meaning: '文化背景', level: 1 },
  { word: 'balance', phonetic: '/ˈbæləns/', meaning: '平衡', phrase: 'keep a balance', phrase_meaning: '保持平衡', level: 1 },
  { word: 'behavior', phonetic: '/bɪˈheɪvjər/', meaning: '行为', phrase: 'social behavior', phrase_meaning: '社会行为', level: 1 },
  { word: 'belief', phonetic: '/bɪˈliːf/', meaning: '信念；信仰', phrase: 'strong belief', phrase_meaning: '坚定信念', level: 1 },
  { word: 'belong', phonetic: '/bɪˈlɔːŋ/', meaning: '属于', phrase: 'belong to', phrase_meaning: '属于', level: 1 },
  { word: 'beyond', phonetic: '/bɪˈjɑːnd/', meaning: '超出；在……之外', phrase: 'beyond doubt', phrase_meaning: '毫无疑问', level: 1 },
  { word: 'brief', phonetic: '/briːf/', meaning: '简短的', phrase: 'in brief', phrase_meaning: '简言之', level: 1 },
  { word: 'career', phonetic: '/kəˈrɪr/', meaning: '职业；生涯', phrase: 'career development', phrase_meaning: '职业发展', level: 1 },
  { word: 'central', phonetic: '/ˈsentrəl/', meaning: '中心的；主要的', phrase: 'central issue', phrase_meaning: '核心问题', level: 1 },
  { word: 'certain', phonetic: '/ˈsɜːrtn/', meaning: '确定的；某些', phrase: 'be certain about', phrase_meaning: '对……有把握', level: 1 },
  { word: 'chance', phonetic: '/tʃæns/', meaning: '机会；可能性', phrase: 'by chance', phrase_meaning: '偶然', level: 1 },
  { word: 'character', phonetic: '/ˈkærəktər/', meaning: '性格；角色；字符', phrase: 'main character', phrase_meaning: '主角', level: 1 },
  { word: 'choice', phonetic: '/tʃɔɪs/', meaning: '选择', phrase: 'make a choice', phrase_meaning: '做选择', level: 1 },
  { word: 'claim', phonetic: '/kleɪm/', meaning: '声称；要求；索赔', phrase: 'claim that', phrase_meaning: '声称', level: 1 },
  { word: 'climate', phonetic: '/ˈklaɪmət/', meaning: '气候', phrase: 'climate change', phrase_meaning: '气候变化', level: 1 },
  { word: 'collect', phonetic: '/kəˈlekt/', meaning: '收集', phrase: 'collect data', phrase_meaning: '收集数据', level: 1 },
  { word: 'combine', phonetic: '/kəmˈbaɪn/', meaning: '结合；组合', phrase: 'combine with', phrase_meaning: '与……结合', level: 1 },
  { word: 'comment', phonetic: '/ˈkɑːment/', meaning: '评论', phrase: 'make a comment', phrase_meaning: '发表评论', level: 1 },
  { word: 'commit', phonetic: '/kəˈmɪt/', meaning: '犯（错误）；承诺', phrase: 'commit to doing', phrase_meaning: '致力于', level: 1 },
  { word: 'communicate', phonetic: '/kəˈmjuːnɪkeɪt/', meaning: '交流；沟通', phrase: 'communicate with', phrase_meaning: '与……交流', level: 1 },
  { word: 'community', phonetic: '/kəˈmjuːnəti/', meaning: '社区；群体', phrase: 'local community', phrase_meaning: '本地社区', level: 1 },
  { word: 'compare', phonetic: '/kəmˈper/', meaning: '比较', phrase: 'compare with', phrase_meaning: '与……比较', level: 1 },
  { word: 'compete', phonetic: '/kəmˈpiːt/', meaning: '竞争', phrase: 'compete with', phrase_meaning: '与……竞争', level: 1 },
  { word: 'complain', phonetic: '/kəmˈpleɪn/', meaning: '抱怨；投诉', phrase: 'complain about', phrase_meaning: '抱怨', level: 1 },
  { word: 'concern', phonetic: '/kənˈsɜːrn/', meaning: '关心；涉及；担忧', phrase: 'be concerned about', phrase_meaning: '担忧', level: 1 },
  { word: 'confident', phonetic: '/ˈkɑːnfɪdənt/', meaning: '自信的；有把握的', phrase: 'be confident in', phrase_meaning: '对……有信心', level: 1 },
  { word: 'confirm', phonetic: '/kənˈfɜːrm/', meaning: '确认；证实', phrase: 'confirm the details', phrase_meaning: '确认细节', level: 1 },
  { word: 'conflict', phonetic: '/ˈkɑːnflɪkt/', meaning: '冲突；矛盾', phrase: 'in conflict with', phrase_meaning: '与……冲突', level: 1 },
  { word: 'connect', phonetic: '/kəˈnekt/', meaning: '连接；联系', phrase: 'connect to', phrase_meaning: '连接到', level: 1 },
  { word: 'consist', phonetic: '/kənˈsɪst/', meaning: '由……组成', phrase: 'consist of', phrase_meaning: '由……组成', level: 1 },
  { word: 'constant', phonetic: '/ˈkɑːnstənt/', meaning: '持续的；不变的', phrase: 'constant change', phrase_meaning: '不断变化', level: 1 },
  { word: 'contact', phonetic: '/ˈkɑːntækt/', meaning: '联系；接触', phrase: 'keep in contact', phrase_meaning: '保持联系', level: 1 },
  { word: 'contain', phonetic: '/kənˈteɪn/', meaning: '包含；容纳', phrase: 'contain information', phrase_meaning: '包含信息', level: 1 },
  { word: 'convince', phonetic: '/kənˈvɪns/', meaning: '使信服', phrase: 'convince sb of', phrase_meaning: '使某人相信', level: 1 },
  { word: 'cooperate', phonetic: '/koʊˈɑːpəreɪt/', meaning: '合作', phrase: 'cooperate with', phrase_meaning: '与……合作', level: 1 },
  { word: 'cope', phonetic: '/koʊp/', meaning: '应付；处理', phrase: 'cope with', phrase_meaning: '应对', level: 1 },
  { word: 'courage', phonetic: '/ˈkɜːrɪdʒ/', meaning: '勇气', phrase: 'have the courage to', phrase_meaning: '有勇气做', level: 1 },
  { word: 'daily', phonetic: '/ˈdeɪli/', meaning: '每日的；日常的', phrase: 'daily routine', phrase_meaning: '日常安排', level: 1 },
  { word: 'damage', phonetic: '/ˈdæmɪdʒ/', meaning: '损害；破坏', phrase: 'cause damage', phrase_meaning: '造成损害', level: 1 },
  { word: 'danger', phonetic: '/ˈdeɪndʒər/', meaning: '危险', phrase: 'in danger', phrase_meaning: '处于危险中', level: 1 },
  { word: 'deal', phonetic: '/diːl/', meaning: '处理；交易', phrase: 'deal with', phrase_meaning: '处理', level: 1 },
  { word: 'defend', phonetic: '/dɪˈfend/', meaning: '防御；辩护', phrase: 'defend against', phrase_meaning: '抵御', level: 1 },
  { word: 'degree', phonetic: '/dɪˈɡriː/', meaning: '程度；学位', phrase: 'to some degree', phrase_meaning: '在某种程度上', level: 1 },
  { word: 'demand', phonetic: '/dɪˈmænd/', meaning: '要求；需求', phrase: 'meet the demand', phrase_meaning: '满足需求', level: 1 },
  { word: 'depend', phonetic: '/dɪˈpend/', meaning: '依赖；取决于', phrase: 'depend on', phrase_meaning: '依赖', level: 1 },
  { word: 'design', phonetic: '/dɪˈzaɪn/', meaning: '设计', phrase: 'design a system', phrase_meaning: '设计系统', level: 1 },
  { word: 'desire', phonetic: '/dɪˈzaɪər/', meaning: '渴望；欲望', phrase: 'desire for', phrase_meaning: '对……的渴望', level: 1 },
  // ===== 2 核心 =====
  { word: 'academic', phonetic: '/ˌækəˈdemɪk/', meaning: '学术的', phrase: 'academic performance', phrase_meaning: '学业表现', level: 2 },
  { word: 'accurate', phonetic: '/ˈækjərət/', meaning: '准确的', phrase: 'accurate data', phrase_meaning: '准确数据', level: 2 },
  { word: 'adequate', phonetic: '/ˈædɪkwət/', meaning: '足够的；适当的', phrase: 'adequate preparation', phrase_meaning: '充分准备', level: 2 },
  { word: 'adjust', phonetic: '/əˈdʒʌst/', meaning: '调整；适应', phrase: 'adjust to', phrase_meaning: '适应', level: 2 },
  { word: 'administration', phonetic: '/ədˌmɪnɪˈstreɪʃn/', meaning: '管理；行政', phrase: 'administration system', phrase_meaning: '管理系统', level: 2 },
  { word: 'afford', phonetic: '/əˈfɔːrd/', meaning: '负担得起；提供', phrase: 'afford to do', phrase_meaning: '有条件做', level: 2 },
  { word: 'agency', phonetic: '/ˈeɪdʒənsi/', meaning: '机构；代理处', phrase: 'government agency', phrase_meaning: '政府机构', level: 2 },
  { word: 'appropriate', phonetic: '/əˈproʊpriət/', meaning: '适当的', phrase: 'appropriate measure', phrase_meaning: '适当措施', level: 2 },
  { word: 'aspect', phonetic: '/ˈæspekt/', meaning: '方面', phrase: 'in many aspects', phrase_meaning: '在许多方面', level: 2 },
  { word: 'assist', phonetic: '/əˈsɪst/', meaning: '帮助；协助', phrase: 'assist with', phrase_meaning: '协助', level: 2 },
  { word: 'attach', phonetic: '/əˈtætʃ/', meaning: '附上；系上', phrase: 'attach importance to', phrase_meaning: '重视', level: 2 },
  { word: 'campaign', phonetic: '/kæmˈpeɪn/', meaning: '运动；活动', phrase: 'launch a campaign', phrase_meaning: '发起运动', level: 2 },
  { word: 'circumstance', phonetic: '/ˈsɜːrkəmstæns/', meaning: '情况；环境', phrase: 'under the circumstances', phrase_meaning: '在这种情况下', level: 2 },
  { word: 'civil', phonetic: '/ˈsɪvl/', meaning: '公民的；民事的', phrase: 'civil society', phrase_meaning: '公民社会', level: 2 },
  { word: 'coherent', phonetic: '/koʊˈhɪrənt/', meaning: '连贯的；一致的', phrase: 'coherent argument', phrase_meaning: '连贯论证', level: 2 },
  { word: 'commitment', phonetic: '/kəˈmɪtmənt/', meaning: '承诺；投入', phrase: 'make a commitment', phrase_meaning: '作出承诺', level: 2 },
  { word: 'compensation', phonetic: '/ˌkɑːmpenˈseɪʃn/', meaning: '补偿；赔偿', phrase: 'financial compensation', phrase_meaning: '经济补偿', level: 2 },
  { word: 'component', phonetic: '/kəmˈpoʊnənt/', meaning: '组成部分；部件', phrase: 'key component', phrase_meaning: '关键部件', level: 2 },
  { word: 'comprehensive', phonetic: '/ˌkɑːmprɪˈhensɪv/', meaning: '全面的；综合的', phrase: 'comprehensive plan', phrase_meaning: '全面计划', level: 2 },
  { word: 'concentrate', phonetic: '/ˈkɑːnsntreɪt/', meaning: '集中；专心', phrase: 'concentrate on', phrase_meaning: '专注于', level: 2 },
  { word: 'confuse', phonetic: '/kənˈfjuːz/', meaning: '使困惑', phrase: 'confuse A with B', phrase_meaning: '把 A 与 B 混淆', level: 2 },
  { word: 'consistent', phonetic: '/kənˈsɪstənt/', meaning: '一致的；始终如一的', phrase: 'consistent with', phrase_meaning: '与……一致', level: 2 },
  { word: 'construct', phonetic: '/kənˈstrʌkt/', meaning: '建造；构建', phrase: 'construct a model', phrase_meaning: '构建模型', level: 2 },
  { word: 'consult', phonetic: '/kənˈsʌlt/', meaning: '咨询；查阅', phrase: 'consult an expert', phrase_meaning: '咨询专家', level: 2 },
  { word: 'consume', phonetic: '/kənˈsuːm/', meaning: '消耗；消费', phrase: 'consume energy', phrase_meaning: '消耗能源', level: 2 },
  { word: 'convey', phonetic: '/kənˈveɪ/', meaning: '传达；运输', phrase: 'convey a message', phrase_meaning: '传达信息', level: 2 },
  { word: 'coordinate', phonetic: '/koʊˈɔːrdɪneɪt/', meaning: '协调', phrase: 'coordinate the work', phrase_meaning: '协调工作', level: 2 },
  { word: 'correspond', phonetic: '/ˌkɔːrəˈspɑːnd/', meaning: '符合；对应', phrase: 'correspond to', phrase_meaning: '与……对应', level: 2 },
  { word: 'crisis', phonetic: '/ˈkraɪsɪs/', meaning: '危机', phrase: 'economic crisis', phrase_meaning: '经济危机', level: 2 },
  { word: 'decade', phonetic: '/ˈdekeɪd/', meaning: '十年', phrase: 'in the past decade', phrase_meaning: '在过去十年', level: 2 },
  { word: 'deliberate', phonetic: '/dɪˈlɪbərət/', meaning: '故意的；深思熟虑的', phrase: 'a deliberate choice', phrase_meaning: '深思熟虑的选择', level: 2 },
  { word: 'deposit', phonetic: '/dɪˈpɑːzɪt/', meaning: '存款；押金', phrase: 'make a deposit', phrase_meaning: '存款', level: 2 },
  { word: 'derive', phonetic: '/dɪˈraɪv/', meaning: '源于；获得', phrase: 'derive from', phrase_meaning: '来源于', level: 2 },
  { word: 'destination', phonetic: '/ˌdestɪˈneɪʃn/', meaning: '目的地', phrase: 'final destination', phrase_meaning: '最终目的地', level: 2 },
  { word: 'diverse', phonetic: '/daɪˈvɜːrs/', meaning: '多样的', phrase: 'diverse cultures', phrase_meaning: '多元文化', level: 2 },
  { word: 'domestic', phonetic: '/dəˈmestɪk/', meaning: '国内的；家庭的', phrase: 'domestic market', phrase_meaning: '国内市场', level: 2 },
  { word: 'dramatic', phonetic: '/drəˈmætɪk/', meaning: '戏剧性的；巨大的', phrase: 'dramatic change', phrase_meaning: '剧变', level: 2 },
  { word: 'ease', phonetic: '/iːz/', meaning: '缓解；轻松', phrase: 'ease the pressure', phrase_meaning: '缓解压力', level: 2 },
  { word: 'emergency', phonetic: '/ɪˈmɜːrdʒənsi/', meaning: '紧急情况', phrase: 'in an emergency', phrase_meaning: '在紧急情况下', level: 2 },
  { word: 'engage', phonetic: '/ɪnˈɡeɪdʒ/', meaning: '从事；参与', phrase: 'engage in', phrase_meaning: '从事', level: 2 },
  // ===== 3 拓展 =====
  { word: 'abundant', phonetic: '/əˈbʌndənt/', meaning: '丰富的；充裕的', phrase: 'abundant resources', phrase_meaning: '丰富的资源', level: 3 },
  { word: 'acknowledge', phonetic: '/əkˈnɑːlɪdʒ/', meaning: '承认；致谢', phrase: 'acknowledge the fact', phrase_meaning: '承认事实', level: 3 },
  { word: 'adequate', phonetic: '/ˈædɪkwət/', meaning: '足够的；适当的', phrase: 'adequate supply', phrase_meaning: '充足供应', level: 3 },
  { word: 'adverse', phonetic: '/ædˈvɜːrs/', meaning: '不利的；相反的', phrase: 'adverse effect', phrase_meaning: '不利影响', level: 3 },
  { word: 'advocate', phonetic: '/ˈædvəkeɪt/', meaning: '提倡；拥护', phrase: 'advocate for', phrase_meaning: '主张', level: 3 },
  { word: 'aesthetic', phonetic: '/esˈθetɪk/', meaning: '美学的', phrase: 'aesthetic value', phrase_meaning: '美学价值', level: 3 },
  { word: 'aggregate', phonetic: '/ˈæɡrɪɡət/', meaning: '总计的；聚合', phrase: 'aggregate data', phrase_meaning: '汇总数据', level: 3 },
  { word: 'alleviate', phonetic: '/əˈliːvieɪt/', meaning: '减轻；缓解', phrase: 'alleviate poverty', phrase_meaning: '缓解贫困', level: 3 },
  { word: 'ambiguous', phonetic: '/æmˈbɪɡjuəs/', meaning: '模糊不清的', phrase: 'ambiguous statement', phrase_meaning: '含糊表述', level: 3 },
  { word: 'amplify', phonetic: '/ˈæmplɪfaɪ/', meaning: '放大；增强', phrase: 'amplify the signal', phrase_meaning: '放大信号', level: 3 },
  { word: 'analogy', phonetic: '/əˈnælədʒi/', meaning: '类比', phrase: 'draw an analogy', phrase_meaning: '作类比', level: 3 },
  { word: 'anonymous', phonetic: '/əˈnɑːnɪməs/', meaning: '匿名的', phrase: 'anonymous survey', phrase_meaning: '匿名调查', level: 3 },
  { word: 'apprehend', phonetic: '/ˌæprɪˈhend/', meaning: '理解；逮捕', phrase: 'apprehend the meaning', phrase_meaning: '理解含义', level: 3 },
  { word: 'articulate', phonetic: '/ɑːrˈtɪkjuleɪt/', meaning: '清晰表达', phrase: 'articulate a view', phrase_meaning: '清晰表达观点', level: 3 },
  { word: 'ascertain', phonetic: '/ˌæsərˈteɪn/', meaning: '查明；确定', phrase: 'ascertain the truth', phrase_meaning: '查明真相', level: 3 },
  { word: 'assumption', phonetic: '/əˈsʌmpʃn/', meaning: '假设；假定', phrase: 'make an assumption', phrase_meaning: '作出假设', level: 3 },
  { word: 'authentic', phonetic: '/ɔːˈθentɪk/', meaning: '真实的；正宗的', phrase: 'authentic experience', phrase_meaning: '真实体验', level: 3 },
  { word: 'autonomy', phonetic: '/ɔːˈtɑːnəmi/', meaning: '自主；自治', phrase: 'personal autonomy', phrase_meaning: '个人自主', level: 3 },
  { word: 'boundary', phonetic: '/ˈbaʊndri/', meaning: '边界；界限', phrase: 'cross the boundary', phrase_meaning: '跨越界限', level: 3 },
  { word: 'coincide', phonetic: '/ˌkoʊɪnˈsaɪd/', meaning: '同时发生；一致', phrase: 'coincide with', phrase_meaning: '与……一致', level: 3 },
];

/** 全部内置词（第一批 120 + 第二批 120，共 240） */
export const ALL_BUILTIN_VOCABULARY: BuiltinWord[] = [...BUILTIN_VOCABULARY, ...BUILTIN_VOCABULARY_2];
